name: Shin Megami Tensei (Japan)
sha1: 81c5e7ee5f5a4e0ff3747c1d1f16c4a9478819ec
options:
  basename: smt1_data
  target_path: game/smt1/DATA.BIN
  elf_path: build/smt1_data.elf
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/smt1/data
  src_path: src/smt1/data
  build_path: build
  asset_path: assets/smt1/data
  # create_asm_dependencies: True

  ld_script_path: config/smt1.data.ld
  ld_dependencies: True

  find_file_boundaries: True
  gp_value: 0x800B6C5C

  o_as_suffix: True
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  symbol_addrs_path:
    - config/symbols.smt1.data.txt
  reloc_addrs_path:
    - config/reloc_addrs.smt1.data.txt

  undefined_funcs_auto_path: config/undefined_funcs_auto.smt1.data.txt
  undefined_syms_auto_path: config/undefined_syms_auto.smt1.data.txt

  extensions_path: tools/splat_ext

  subalign: 0x800

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - [0x0, bin]
  - [0xe000, bin]
  - [0x18000, bin]
  - [0x20800, bin]
  - [0x22000, bin]
  - [0x2f800, bin]
  - [0x33800, bin]
  - name: intro
    type: code
    start: 0x36000
    vram: 0x80180000
    subalign: 4
    subsegments:
      - [0x36000, .data]
      - [0x366e0, c]
      - [0x3b2a0, .rodata]
      - [0x3b404, pad]

  - [0x3b800, bin, tex/map]
  - [0x3d000, bin]
  - [0x43000, bin]
  - [0x58000, bin]
  - [0x5a000, bin]
  - [0x5e000, bin]
  - [0x5e800, bin]
  - [0x63000, bin]
  - [0x67000, bin]
  - [0x68800, bin]
  - [0x6a000, bin]
  - [0x6b800, bin]
  - [0x6d000, bin]
  - [0x6e800, bin]
  - [0x70000, bin]
  - [0x71800, bin]
  - [0x73000, bin]
  - [0x73800, bin]
  - [0x74800, bin]
  - [0x79800, bin]
  - [0x7b800, bin]
  - [0x7d000, bin]
  - [0x7d800, bin]
  - [0x7e000, bin]
  - [0x7e800, bin]
  - [0x80000, bin]
  - [0x80800, bin, tex/rnd1]
  - [0x85800, bin, tex/titlel]
  - [0x8a800, bin, tex/titler]
  - [0x8f800, bin, tex/logo]
  - [0x94000, bin]
  - [0x96000, bin]
  - [0x97800, bin]
  - [0x99000, bin]
  - [0x99800, bin]
  - [0x9a000, bin]
  - [0x9a800, bin, tex/fusecaps]
  - [0xa3800, bin, tex/fusebubl]
  - [0xad000, bin, tex/flash]
  - [0xb6800, bin, tex/countdwn]
  - [0xb7800, bin]
  - [0xb8000, bin]
  - [0xba800, bin]
  - [0xbc000, bin]
  - [0xbd800, bin]
  - [0xbe800, bin]
  - [0xbf000, bin]
  - [0xbf800, bin]
  - [0xc0800, bin]
  - [0xc2800, bin]
  - [0xc8800, bin]
  - [0xc9800, bin]
  - [0xcc000, bin]
  - [0xcc800, bin]
  - [0xcd800, bin]
  - [0xce800, bin]
  - [0xcf800, bin]
  - [0xd3000, bin]
  - [0xd3800, bin]
  - [0xd6800, bin]
  - [0xd8000, bin]
  - [0xdc800, bin]
  - [0xde800, bin]
  - [0xe1000, bin]
  - [0xe2800, bin]
  - [0xe3800, bin]
  - [0xe4000, bin]
  - [0xe5800, bin]
  - [0xe7800, bin]
  - [0xe8000, bin]
  - [0xe9800, bin]
  - [0xea800, bin]
  - [0xeb000, bin]
  - [0xec000, bin]
  - [0xec800, bin]
  - [0xed800, bin]
  - [0xee800, bin]
  - [0xef800, bin]
  - [0xf0800, bin]
  - [0xf1800, bin]
  - [0xf2800, bin]
  - [0xf3800, bin, tex/bg/jakyol]
  - [0xff800, bin, tex/bg/jakyor]
  - [0x10b800, bin, tex/bg/mesial]
  - [0x117800, bin, tex/bg/mesiar]
  - [0x123800, bin, tex/bg/gaial]
  - [0x12f800, bin, tex/bg/gaiar]
  - [0x13b800, bin, tex/bg/kaifukul]
  - [0x147800, bin, tex/bg/kaifukur]
  - [0x153800, bin, tex/bg/terml]
  - [0x15f800, bin, tex/bg/termr]
  - [0x16b800, bin, tex/bg/rooml]
  - [0x177800, bin, tex/bg/roomr]
  - [0x183800, bin, tex/bg/hospl]
  - [0x18f800, bin, tex/bg/hospr]
  - [0x19b800, bin, tex/bg/brooml]
  - [0x1a7800, bin, tex/bg/broomr]
  - [0x1b3800, bin, tex/bg/homel]
  - [0x1bf800, bin, tex/bg/homer]
  - [0x1cb800, bin, tex/bg/gbrooml]
  - [0x1d7800, bin, tex/bg/gbroomr]
  - [0x1e3800, bin, tex/bg/oprooml]
  - [0x1ef800, bin, tex/bg/oproomr]
  - [0x1fb800, bin, tex/bg/shuttrl]
  - [0x207800, bin, tex/bg/shuttrr]
  - [0x213800, bin, tex/bg/doorl]
  - [0x21f800, bin, tex/bg/doorr]
  - [0x22b800, bin, tex/bg/ddoorl]
  - [0x237800, bin, tex/bg/ddoorr]
  - [0x243800, bin, tex/bg/dshuttrl]
  - [0x24f800, bin, tex/bg/dshuttrr]
  - [0x25b800, bin, tex/bg/grooml]
  - [0x269000, bin, tex/bg/groomr]
  - [0x275000, bin, tex/bg/embassyl]
  - [0x288800, bin, tex/bg/embassyr]
  - [0x294800, bin, tex/bg/st0l]
  - [0x2a0800, bin, tex/bg/st0r]
  - [0x2b4000, bin, tex/bg/lakel]
  - [0x2c0000, bin, tex/bg/laker]
  - [0x2cc000, bin, tex/bg/cereml]
  - [0x2d8000, bin, tex/bg/ceremr]
  - [0x2e4000, bin, tex/bg/shrinel]
  - [0x2f0000, bin, tex/bg/shriner]
  - [0x2fc000, bin, tex/bg/endl]
  - [0x308000, bin, tex/bg/endr]
  - [0x314000, bin, tex/bg/chikyul]
  - [0x320000, bin, tex/bg/chikyur]
  - [0x330000, bin, tex/bg/galaxyl]
  - [0x340000, bin, tex/bg/galaxyr]
  - [0x34c000, bin, tex/bg/bar1l]
  - [0x358000, bin, tex/bg/bar1r]
  - [0x364000, bin, tex/bg/bar2l]
  - [0x370000, bin, tex/bg/bar2r]
  - [0x37d800, bin, tex/bg/antiquel]
  - [0x389800, bin, tex/bg/antiquer]
  - [0x395800, bin, tex/bg/drugl]
  - [0x3a1800, bin, tex/bg/drugr]
  - [0x3ad800, bin, tex/bg/knivel]
  - [0x3b9800, bin, tex/bg/kniver]
  - [0x3c5800, bin, tex/bg/surviv1l]
  - [0x3d5800, bin, tex/bg/surviv1r]
  - [0x3e5800, bin, tex/bg/nendl]
  - [0x3f9000, bin, tex/bg/nendr]
  - [0x40c800, bin, tex/bg/wasitul]
  - [0x418800, bin, tex/bg/wasitur]
  - [0x424800, bin, tex/bg/sibuya1l]
  - [0x430800, bin, tex/bg/sibuya1r]
  - [0x43c800, bin, tex/bg/exect1l]
  - [0x448800, bin, tex/bg/exect1r]
  - [0x454800, bin, tex/bg/exect2l]
  - [0x460800, bin, tex/bg/exect2r]
  - [0x46c800, bin, tex/bg/sibuya2l]
  - [0x478800, bin, tex/bg/sibuya2r]
  - [0x484800, bin, tex/bg/tkrooml]
  - [0x490800, bin, tex/bg/tkroomr]
  - [0x49c800, bin, tex/bg/junkl]
  - [0x4a8800, bin, tex/bg/junkr]
  - [0x4b4800, bin, tex/bg/gunl]
  - [0x4c0800, bin, tex/bg/gunr]
  - [0x4cc800, bin, tex/bg/surviv2l]
  - [0x4d8800, bin, tex/bg/surviv2r]
  - [0x4e4800, bin, tex/bg/shopl]
  - [0x4f0800, bin, tex/bg/shopr]
  - [0x4fc800, bin, tex/bg/palacel]
  - [0x508800, bin, tex/bg/palacer]
  - [0x514800, bin, tex/bg/prisonl]
  - [0x520800, bin, tex/bg/prisonr]
  - [0x52c800, bin, tex/bg/constrl]
  - [0x538800, bin, tex/bg/constrr]
  - [0x544800, bin, tex/bg/thronel]
  - [0x550800, bin, tex/bg/throner]
  - [0x55c800, bin, tex/bg/cathl]
  - [0x568800, bin, tex/bg/cathr]
  - [0x574800, bin, tex/bg/gcathl]
  - [0x580800, bin, tex/bg/gcathr]
  - [0x58c800, bin]
  - [0x598800, bin]
  - [0x5a4800, bin]
  - [0x5b0800, bin]
  - [0x5d4800, bin]
  - [0x5e0800, bin]
  - [0x5f8800, bin]
  - [0x604800, bin]
  - [0x610800, bin]
  - [0x61c800, bin]
  - [0x628800, bin]
  - [0x634800, bin]
  - [0x640800, bin]
  - [0x64c800, bin]
  - [0x658800, bin]
  - [0x664800, bin]
  - [0x670800, bin]
  - [0x67c800, bin]
  - [0x688800, bin]
  - [0x694800, bin]
  - [0x6a0800, bin]
  - [0x6ac800, bin]
  - [0x6b8800, bin]
  - [0x6c4800, bin]
  - [0x6d0800, bin]
  - [0x6dc800, bin]
  - [0x6e8800, bin]
  - [0x6f4800, bin]
  - [0x700800, bin]
  - [0x70c800, bin]
  - [0x718800, bin]
  - [0x724800, bin]
  - [0x730800, bin]
  - [0x73c800, bin]
  - [0x748800, bin]
  - [0x754800, bin]
  - [0x760800, bin]
  - [0x76c800, bin]
  - [0x778800, bin]
  - [0x784800, bin]
  - [0x790800, bin]
  - [0x79c800, bin]
  - [0x7a8800, bin]
  - [0x7b4800, bin]
  - [0x7c0800, bin]
  - [0x7cc800, bin]
  - [0x7d8800, bin]
  - [0x7e4800, bin]
  - [0x7f0800, bin]
  - [0x7fc800, bin]
  - [0x808800, bin]
  - [0x814800, bin]
  - [0x81d000, bin]
  - [0x825800, bin]
  - [0x82e000, bin]
  - [0x836800, bin]
  - [0x83f000, bin]
  - [0x842000, bin, field/ktjj]
  - [0x845000, bin, field/unk]
  - [0x84d800, bin]
  - [0x854000, bin]
  - [0x857800, bin]
  - [0x866800, bin]
  - [0x869800, bin]
  - [0x86f800, bin]
  - [0x873000, bin]
  - [0x882800, bin]
  - [0x885800, bin]
  - [0x896800, bin]
  - [0x899800, bin]
  - [0x8a9800, bin]
  - [0x8ac800, bin]
  - [0x8b4800, bin]
  - [0x8b7800, bin]
  - [0x8c0800, bin]
  - [0x8c3800, bin]
  - [0x8cb800, bin]
  - [0x8cf000, bin]
  - [0x8dd800, bin]
  - [0x8e0800, bin]
  - [0x8ea000, bin]
  - [0x8ed000, bin]
  - [0x8fc800, bin]
  - [0x8ff800, bin]
  - [0x910000, bin]
  - [0x913000, bin]
  - [0x923800, bin]
  - [0x926800, bin]
  - [0x934000, bin]
  - [0x937800, bin]
  - [0x948800, bin]
  - [0x94b800, bin]
  - [0x95c800, bin]
  - [0x95f000, bin]
  - [0x96d000, bin]
  - [0x96f800, bin]
  - [0x97b800, bin]
  - [0x97e800, bin]
  - [0x986800, bin]
  - [0x989800, bin]
  - [0x99b000, bin]
  - [0x99e000, bin]
  - [0x9a7000, bin]
  - [0x9aa000, bin]
  - [0x9bb800, bin]
  - [0x9be800, bin]
  - [0x9c7800, bin]
  - [0x9ca800, bin]
  - [0x9db000, bin]
  - [0x9de800, bin]
  - [0x9e5800, bin]
  - [0x9e8800, bin]
  - [0x9f0800, bin]
  - [0x9f3800, bin]
  - [0x9fb800, bin]
  - [0x9fe800, bin]
  - [0xa0e800, bin]
  - [0xa11800, bin]
  - [0xa21000, bin]
  - [0xa24000, bin]
  - [0xa33800, bin]
  - [0xa36800, bin]
  - [0xa46000, bin]
  - [0xa49000, bin]
  - [0xa57800, bin]
  - [0xa5b000, bin]
  - [0xa61000, bin]
  - [0xa64800, bin]
  - [0xa6f000, bin]
  - [0xa76000, bin]
  - [0xa79800, bin]
  - [0xa80800, bin]
  - [0xa84000, bin]
  - [0xa93800, bin]
  - [0xa95800, bin]
  - [0xa9c800, bin]
  - [0xa9e800, bin]
  - [0xaa8000, bin]
  - [0xab4000, bin]
  - [0xab6800, bin]
  - [0xac2800, bin]
  - [0xac6000, bin]
  - [0xacf000, bin]
  - [0xad2800, bin]
  - [0xadc000, bin]
  - [0xadf800, bin]
  - [0xae8800, bin]
  - [0xaea800, bin]
  - [0xaec800, bin]
  - [0xaee800, bin]
  - [0xaf1000, bin]
  - [0xaf3000, bin]
  - [0xaf5000, bin]
  - [0xaf6800, bin]
  - [0xaf8800, bin]
  - [0xafa800, bin]
  - [0xafc800, bin]
  - [0xafe800, bin]
  - [0xb00800, bin]
  - [0xb02800, bin]
  - [0xb04800, bin]
  - [0xb06800, bin]
  - [0xb08800, bin]
  - [0xb0a800, bin]
  - [0xb0c800, bin]
  - [0xb0e800, bin]
  - [0xb0f800, bin]
  - [0xb11000, bin]
  - [0xb11800, bin]
  - [0xb12800, bin]
  - [0xb14000, bin]
  - [0xb1c800, bin]
  - [0xb25000, bin]
  - [0xb2d800, bin]
  - [0xb36000, bin]
  - [0xb3e800, bin]
  - [0xb47000, bin]
  - [0xb4f800, bin]
  - [0xb58000, bin]
  - [0xb60800, bin]
  - [0xb69000, bin]
  - [0xb71800, bin]
  - [0xb7a000, bin]
  - [0xb82800, bin]
  - [0xb8b000, bin]
  - [0xb93800, bin]
  - [0xb9c000, bin]
  - [0xba4800, bin]
  - [0xbad000, bin]
  - [0xbb5800, bin]
  - [0xbbe000, bin]
  - [0xbc6800, bin]
  - [0xbcf000, bin]
  - [0xbd7800, bin]
  - [0xbe0000, bin]
  - [0xbe8800, bin]
  - [0xbf1000, bin]
  - [0xc02000, bin]
  - [0xc0a800, bin]
  - [0xc13000, bin]
  - [0xc1b800, bin]
  - [0xc24000, bin]
  - [0xc2c800, bin]
  - [0xc35000, bin]
  - [0xc3d800, bin]
  - [0xc46000, bin]
  - [0xc4e800, bin]
  - [0xc57000, bin]
  - [0xc5f800, bin]
  - [0xc68000, bin]
  - [0xc70800, bin]
  - [0xc79000, bin]
  - [0xc81800, bin]
  - [0xc8a000, bin]
  - [0xc92800, bin]
  - [0xc9b000, bin]
  - [0xca3800, bin]
  - [0xcac000, bin]
  - [0xcb4800, bin]
  - [0xcbd000, bin]
  - [0xcc5800, bin]
  - [0xcce000, bin]
  - [0xcd6800, bin]
  - [0xcdf000, bin]
  - [0xce7800, bin]
  - [0xcf0000, bin]
  - [0xcf8800, bin]
  - [0xd01000, bin]
  - [0xd09800, bin]
  - [0xd12000, bin]
  - [0xd1a800, bin]
  - [0xd23000, bin]
  - [0xd2b800, bin]
  - [0xd34000, bin]
  - [0xd3c800, bin]
  - [0xd45000, bin]
  - [0xd4d800, bin]
  - [0xd56000, bin]
  - [0xd5e800, bin]
  - [0xd67000, bin]
  - [0xd6f800, bin]
  - [0xd78000, bin]
  - [0xd80800, bin]
  - [0xd89000, bin]
  - [0xd91800, bin]
  - [0xd9a000, bin]
  - [0xda2800, bin]
  - [0xdab000, bin]
  - [0xdb3800, bin]
  - [0xdbc000, bin]
  - [0xdc4800, bin]
  - [0xdcd000, bin]
  - [0xdd5800, bin]
  - [0xdde000, bin]
  - [0xde6800, bin]
  - [0xdef000, bin]
  - [0xdf7800, bin]
  - [0xe00000, bin]
  - [0xe08800, bin]
  - [0xe11000, bin]
  - [0xe19800, bin]
  - [0xe22000, bin]
  - [0xe2a800, bin]
  - [0xe33000, bin]
  - [0xe3b800, bin]
  - [0xe44000, bin]
  - [0xe4c800, bin]
  - [0xe55000, bin]
  - [0xe5d800, bin]
  - [0xe66000, bin]
  - [0xe6e800, bin]
  - [0xe77000, bin]
  - [0xe7f800, bin]
  - [0xe88000, bin]
  - [0xe90800, bin]
  - [0xe99000, bin]
  - [0xea1800, bin]
  - [0xeaa000, bin]
  - [0xeb2800, bin]
  - [0xebb000, bin]
  - [0xec3800, bin]
  - [0xecc000, bin]
  - [0xed4800, bin]
  - [0xedd000, bin]
  - [0xee5800, bin]
  - [0xeee000, bin]
  - [0xef6800, bin]
  - [0xeff000, bin]
  - [0xf07800, bin]
  - [0xf10000, bin]
  - [0xf18800, bin]
  - [0xf21000, bin]
  - [0xf29800, bin]
  - [0xf32000, bin]
  - [0xf3a800, bin]
  - [0xf43000, bin]
  - [0xf4b800, bin]
  - [0xf54000, bin]
  - [0xf5c800, bin]
  - [0xf65000, bin]
  - [0xf6d800, bin]
  - [0xf76000, bin]
  - [0xf7e800, bin]
  - [0xf88000, bin]
  - [0xf91800, bin]
  - [0xf9b000, bin]
  - [0xfa4800, bin]
  - [0xfae000, bin]
  - [0xfb7800, bin]
  - [0xfc1000, bin]
  - [0xfca800, bin]
  - [0xfd4000, bin]
  - [0xfdd800, bin]
  - [0xfe7000, bin]
  - [0xff0800, bin]
  - [0xffa000, bin]
  - [0x137b000, bin, seq/effect]
  - [0x13bd800, bin, seq/mus/open]
  - [0x13ce800, bin, seq/mus/title]
  - [0x13df000, bin, seq/mus/dream]
  - [0x13f5800, bin, seq/mus/home]
  - [0x1411000, bin, seq/mus/kichijoj]
  - [0x142b000, bin, seq/mus/arcade]
  - [0x1438800, bin, seq/mus/neutral]
  - [0x1450800, bin, seq/mus/embassy]
  - [0x145b000, bin, seq/mus/shop]
  - [0x146b800, bin, seq/mus/terminal]
  - [0x1477000, bin, seq/mus/palace]
  - [0x147f000, bin, seq/mus/battle]
  - [0x14a0000, bin, seq/mus/law]
  - [0x14ba000, bin, seq/mus/ginza]
  - [0x14d5800, bin, seq/mus/jakyo]
  - [0x14f1000, bin, seq/mus/shibuya]
  - [0x14fc800, bin, seq/mus/boss]
  - [0x1517800, bin, seq/mus/gover]
  - [0x1521000, bin, seq/mus/ruins]
  - [0x152c800, bin, seq/mus/chaos]
  - [0x1539800, bin, seq/mus/cathedrl]
  - [0x1550000, bin, seq/mus/end]
  - [0x155b000, bin, seq/mus/credits]
  - [0x157a800, bin, seq/mus/pascal]
  - [0x158b800, bin, seq/mus/majin]
  - [0x15a6000, bin]
  - [0x15b7000, bin]
  - [0x15cd000, bin]

      
  - [0x1fa0000]