#include "main.h"
#include "lib/memory.h"

/* sdata */
s32 D_800B6C5C = 0;											   /* 0x800B6C5C */
struct pos_pair D_800B6C60 = {0x0018, 0x0088, 0x0018, 0x006F}; /* 0x800B6C60 */
/* bss */
struct persistent_objects PersistentObjects; /* 0x800B74C0 */

/* This function exists but seems to have been generated by the compiler
 * automatically or written in assembly. */
void start(void) {}

/* 100% */
int main(void) {
	Init();
	MainLoop();
	Empty();
	return 0;
}

/* Matched by anon */
/* externs: D_800B6C54, D_800B6C58 */
/* Initializes everything needed for the game to function. */
void Init(void) {
	SysInit();

	/*
		Creates the data table at 0x80125790. Possibly the remains of an
		unimplemented feature, as this code evaluates to the same result every
		time.
	*/
	{
		s32 temp_a0_2;
		u32 temp_a0;
		void * temp_v0;
		u32 tmp;
		s32 rem;

		D_800B6C58 = 0x200000;
		D_800B6C54 = 0x8000;
		temp_v0 = &D_80125368 - D_80010308; /* 0xDBD8 */
		temp_a0 = (u32)temp_v0 / 0x800;		/* 0x1B */
		rem = (u32)temp_v0 % 0x800;			/* 0x3D8 */
		tmp = 0x80000000;

		temp_a0_2 = D_80010308 + (rem != 0 ? temp_a0 + 1 : temp_a0) * 0x800; /* 0x80125790 */
		temp_a0_2 += (8 - (temp_a0_2 & 7)) & 7;								 /* 0 */
		func_80019384(temp_a0_2, D_800B6C58 + tmp - temp_a0_2 - D_800B6C54); /* 0x80125790, 0xD2870 */
	}

	func_80017FF0((void(*))Random, 0);
	VSyncCallback(VSyncCallbackFunc);		/* Set the V-Sync callback function. */
	DrawSyncCallback(DrawSyncCallbackFunc); /* Set the draw sync callback function. */
	SetDispMask(1);							/* Begin displaying things on the screen. */
	VSync(0);								/* Wait for the next frame to be drawn. */
	GameInit();
}

/* 100% */
/* The primary game logic loop, run every frame after initialization. */
void MainLoop(void) {
	while (1) {
		func_80018D44();
		func_8001A54C();
		func_8001847C();
		func_80019958();
		DrawSync(0); /* Wait until drawing has finished. */
		VSync(2);	 /* Wait for the second v-blank period. */
		func_800186A0();
		func_80040788();
		func_8001A610();
		func_80021CB0();
	}
}

/* 100% */
/* Empty function. */
void Empty(void) { return; }

/* 100% */
void SysInit(void) {
	ResetCallback(); /* Reset all system callbacks. */
	func_8001A454();
	func_8003F2B8();
	func_800198BC();
	func_80062318();
	func_80018C3C();
	StartRCnt(0); /* Enable interrupts from root counter 0. */
}

/* 100% */
/* Function to be run when v-blank starts. */
void VSyncCallbackFunc(void) {
	func_8003F9B8();
	SsSeqCalledTbyT(); /* Update sound driver. */
	func_8004F854();
}

/* 100% */
/* Function to be run after draw sync is finished. */
void DrawSyncCallbackFunc(void) { return; }

/* 100% */
/* Fetch a random integer value. */
u32 Random(struct object * self) { return rand(); }

/* 100% */
/* externs: D_80010308, FirstObjectPtrPtr */
struct object * GameInit(void) {
	struct intro_manager * temp_s0;

	func_80018F6C(0, 0);
	func_80040A08(-1);

	bzero((u8 *)&PersistentObjects, sizeof(PersistentObjects));
	PersistentObjects.screen_overlay = func_8001F5EC();
	PersistentObjects.party_hud = func_800253E8(0);
	PersistentObjects.moon_hud = func_8002276C();
	PersistentObjects.money_hud = func_80022B2C();
	PersistentObjects.mag_hud = func_80022DFC();
	PersistentObjects.nav_hud = func_80023148();
	PersistentObjects.enc_bar = func_80023838();
	PersistentObjects.field_char = func_80023F94();
	PersistentObjects.border = func_800245D0();
	PersistentObjects.unk0 = func_800527E8();

	GameDataInit();
	PersistentObjects.intro_manager = CreateObject(IntroManagerProc, EmptyProc,
		FirstObjectPtrPtr->first, 1, 0, sizeof(struct intro_manager));
	temp_s0 = PersistentObjects.intro_manager->data;
	bzero((u8 *)temp_s0, sizeof(*temp_s0));
	temp_s0->data_struct = func_80019C58(0, (void *)D_80010308, 7, 0, 0, 1);

	return PersistentObjects.intro_manager; /* Discarded. */
}

/* 100% */
/* Procedure function for the intro manager object. */
void IntroManagerProc(struct object * self) {
	struct intro_manager * data;

	data = self->data;
	switch (data->frame_counter) {
	case 0:
		func_80018F6C(0, 1);
		data->frame_counter += 1;
	case 1: /* When this case is true it causes the Atlus intro to play. */
		if (func_80019ECC(data->data_struct) != 0) {
			data->obj = func_80117E70(data->unk8);
			data->frame_counter += 1;
		case 2:
			if (data->obj->hidden == 1) {
				RemoveObject(data->obj);
				data->obj = NULL;
				data->frame_counter += 1;
			case 3:
				func_800529E8(PersistentObjects.unk0);
				func_8004407C();
			}
		}
		return;
	}
}

/* 100% */
/* Seems to be responsible for restarting the intro sequence. */
void func_800144D4(s8 arg0) {
	struct intro_manager * data;

	data = PersistentObjects.intro_manager->data;
	data->frame_counter = 1;
	data->unk8 = arg0;
	data->data_struct = func_80019C58(0, (void *)D_80010308, 7, 0, 0, 1);
}

/* 100% */
void EmptyProc(struct object * self) { return; }

/* 100% */
void GameDataInit(void) {
	func_80044178();
	ClearUnknownStruct();
	func_8004BBC0();
	func_80044F94();
	func_8003A094();
	func_80049A34();
	func_8004403C();
	func_80026BEC();
	func_80025308(0);
	func_800225C8(3, 3, 3, 3, 3);
	func_80024484(3);
	func_80024648(3);
	func_8005645C();
}

/* 100% */
/* Matched by MrSapps */
void func_800145CC(s32 (*arg0)(void)) {
	struct object * obj;
	struct unk_data_0 * data;

	func_80018F6C(0, 0);
	obj = CreateObject(func_80014698, NULL, FirstObjectPtrPtr->first, -3, 0,
		sizeof(struct unk_data_0));
	if (obj == NULL)
		return;
	data = obj->data;
	data->counter = 0;
	data->unk0 = arg0;
	func_80044318(1);
	PersistentObjects.unk0->flags = 0x82;
	func_8004018C(func_800408BC(0), 60, 0, 3);
	func_8004018C(func_800408BC(1), 60, 0, 3);
	func_80040A08(2);
	func_8001F6B8();
}

/* 100% */
void func_80014698(struct object * self) {
	struct unk_data_0 * data;

	data = self->data;
	switch (data->counter) { /* irregular */
	case 0:
		if (func_8001F920() == 2) {
			func_80044178();
			ClearUnknownStruct();
			data->counter += 1;
		}
		break;
	case 1:
		func_800187AC(0x10, 0x0FFFFFFF);
		func_800187AC(-4, -4);
		data->counter += 1;
		break;
	case 2:
		if (func_80018774() <= 0) {
			if ((data->unk0 == NULL) || (data->unk0() == 0)) {
				GameDataInit();
				data->counter += 1;
			}
		}
		break;
	case 3:
		RemoveObject(self);
		func_80040A08(-1);
		func_80018F6C(0, 1);
		func_8001F7A0(0, 1);
		func_800144D4(1);
		break;
	}
}

/* 100% */
/* Matched by Mc-muffin */
s32 func_800147CC(void) {
	if (func_8004C06C(0xFE) == 0) {
		func_800145CC(func_80014804);
		return 1;
	}
	return 0;
}

/* 100% */
s32 func_80014804(void) {
	if (D_800B6C5C == 0) {
		func_80040A08(-1);
		func_80040204(20);
		func_80040A08(2);
		D_800B6C5C += 1;
	} else {
		if (func_80040A68(0) == 0) {
			func_80046FF0(3, 1);
			func_80040A08(-1);
			func_8004018C(20, 60, 0, 3);
			func_80040A08(2);
			D_800B6C5C = 0;
			return 0;
		}
		return 1; /* This is redundant but required for the function to match.
				   */
	}
	return 1;
}

/* 100% */
void func_8001489C(s32 arg0, s32 arg1, s32 arg2) {
	func_80052910(PersistentObjects.unk0, arg0, arg1, 0, arg2);
}

/* 100% */
void func_800148D4(void) { func_8005286C(PersistentObjects.unk0); }

/* 100% */
void func_800148FC(s32 arg0) { func_80052890(PersistentObjects.unk0, arg0); }

/* 100% */
void func_80014928(s32 arg0) {
	u16 temp_v0;
	struct unknown_object_struct * temp_sp;

	temp_sp = PersistentObjects.unk0;
	temp_sp->unk8A = temp_sp->unk10[arg0];
	temp_sp->unk88 = temp_sp->unk10[arg0];
	PersistentObjects.unk0->flags = 2;
}

/* 100% */
struct object * func_80014964(void) { return PersistentObjects.unk0->sprite9; }

/* 100% */
void ClearUnknownStruct(void) {
	func_80052BF0(PersistentObjects.unk0);
	func_80019478(PersistentObjects.unk0->unk4);
	PersistentObjects.unk0->unk4 = NULL;
	PersistentObjects.unk0->unk4 = NULL;
	PersistentObjects.unk0->flags = 0x80;
}

/* 100% */
/* Sets PersistentObjects.unk1 to the provided value. */
void func_800149E4(u32 * arg0) { PersistentObjects.unk1 = arg0; }

/* 100% */
u32 * func_800149F0(s32 arg0) {
	return &PersistentObjects.unk1[PersistentObjects.unk1[arg0] >> 2];
}

/* 100% */
/* Gets if the provided unk_data_1 object's unk269 field is equal to 0. */
s32 func_80014A18(struct object * arg0) {
	return ((struct unk_data_1 *)arg0->data)->unk269 == 0;
}

/* 100% */
struct object * func_80014A2C(void) {
	struct object * temp_v0;

	temp_v0 = CreateObject(func_80014AF4, NULL, FirstObjectPtrPtr->first,
		0xC00000, 0, sizeof(struct unk_data_1));
	if (temp_v0 == NULL)
		return NULL;
	bzero(temp_v0->data, sizeof(struct unk_data_1));
	func_800225C8(1, 1, 1, 1, 2);
	func_8001F984(0, 0, 320, 240, 0, 0x40404040, 2, 8, 24);
	return temp_v0;
}

/* 100% */
void func_80014AF4(struct object * arg0) {
	struct unk_data_2 * temp_s0;
	struct unk_data_1 * temp_s1;
	void (*sp[3])(struct object *) = {func_80014E34, func_80014F44, func_800150A0};

	temp_s1 = arg0->data;
	switch (temp_s1->counter) { /* irregular */
	case 0:
		temp_s1->unk0 = func_8001513C(temp_s1);
		func_80018CEC();
		temp_s1->counter += 1;
	case 1:
		temp_s0 = temp_s1->unk0->data;
		if (func_80018F14(0, 12) != 0) {
			temp_s1->buffer ^= 1;
		}
		if (func_80018F14(0, 3) != 0) {
			temp_s0->field39_0x28 = 0;
		}
		if (temp_s1->buffer != 0) {
			func_80014CD4(temp_s1, temp_s0->field38_0x26);
		}
		if (temp_s0->field42_0x2c != 0) {
			switch (temp_s0->field39_0x28) { /* switch 1; irregular */
			case 1:							 /* switch 1 */
				arg0->proc_func = sp[temp_s0->field38_0x26];
				break;
			case 2: /* switch 1 */
			case 0: /* switch 1 */
				temp_s1->unk269 = 1;
				if (func_80044114() == 0) {
					func_800225C8(0, 1, 1, 0, 0);
				} else {
					func_800225C8(0, 1, 0, 0, 0);
				}
				func_8001F984(0, 0, 320, 240, 0x40404040, 0, 2, 8, 24);
				break;
			}
			RemoveObject(temp_s1->unk0);
			temp_s1->unk0 = NULL;
			temp_s1->counter = 0;
		}
		return;
	}
}

/* 100% */
void func_80014CD4(struct unk_data_1 * arg0, s32 arg1) {
	struct pos_pair pos_lookup;
	s32 temp_s0;
	DVECTOR * temp_s0_2;
	u16 * temp;

	pos_lookup = D_800B6C60;
	temp_s0 = func_80044114() == 0;
	temp = func_8004B888(arg1 + 772);
	temp_s0_2 = &pos_lookup.pos[temp_s0];
	func_80021DBC(temp, temp_s0_2->vx + 4, temp_s0_2->vy + 2, 5, 0, 0, 21);
	if (func_80044114() == 0) {
		func_80020AAC(temp_s0_2->vx, temp_s0_2->vy, 272, 16, 21, &arg0->f[arg0->buffer], 0);
	} else {
		func_800209F0(temp_s0_2->vx, temp_s0_2->vy, 272, 16, 21, &arg0->g[arg0->buffer], 1);
	}
	arg0->buffer ^= 1;
}

/* 100% */
void func_80014E34(struct object * arg0) {
	void * temp_s1;
	struct unk_data_1 * temp_s0;

	temp_s0 = arg0->data;
	switch (temp_s0->counter) { /* irregular */
	case 0:
		temp_s0->unk0 = func_8005B67C(2, 0, 0x900000);
		temp_s0->counter += 1;
	case 1:
		temp_s1 = temp_s0->unk0->data;
		if (func_8005D870(temp_s1) != 0) {
			if (func_8005D8BC(temp_s1) != 0) {
				func_800145CC(NULL);
				arg0->proc_func = 0;
				return;
			}
			func_8004440C();
			temp_s0->counter += 1;
		case 2:
			if (func_80040A68(0) == 0) {
				arg0->proc_func = &func_80014AF4;
				RemoveObject(temp_s0->unk0);
				temp_s0->unk0 = NULL;
				temp_s0->counter = 0;
			}
		} else {
			return;
		}
		break;
	}
}

/* 100% */
void func_80014F44(struct object * arg0) {
	void * temp_s1;
	struct unk_data_1 * temp_s0;
	u32 * temp_v0;

	temp_s0 = arg0->data;
	switch (temp_s0->counter) {
	case 0:
		temp_s0->unk0 = func_8005B67C(3, 0, 0x900000);
		temp_s0->counter += 1;
	case 1:
		temp_s1 = temp_s0->unk0->data;
		if (func_8005D870(temp_s1) != 0) {
			if (func_8005D8BC(temp_s1) == 0) {
				func_8004440C();
				temp_s0->counter = 3;
				return;
			}
			func_8001F6B8();
			temp_s0->counter += 1;
		case 2:
			if (func_8001F920() == 2) {
				RemoveObject(temp_s0->unk0);
				RemoveObject(arg0);
				temp_v0 = func_8004C5A8();
				func_800441F0(temp_v0[1], temp_v0);
				return;
			}
		} else {
			return;
		}
		break;
	case 3:
		if (func_80040A68(0) == 0) {
			arg0->proc_func = func_80014AF4;
			RemoveObject(temp_s0->unk0);
			temp_s0->counter = 0;
		}
		break;
	}
}

/* 100% */
void func_800150A0(struct object * arg0) {
	struct unk_data_1 * temp_s0;

	temp_s0 = arg0->data;
	switch (temp_s0->counter) { /* irregular */
	case 0:
		temp_s0->unk0 = func_800494D0(0xC00000);
		temp_s0->counter += 1;
	case 1:
		if (temp_s0->unk0->initialized != 1) {
			arg0->proc_func = func_80014AF4;
			RemoveObject(temp_s0->unk0);
			temp_s0->unk0 = NULL;
			temp_s0->counter = 0;
		}
		return;
	}
}

/* 100% */
struct object * func_8001513C(struct unk_data_1 * arg0) {
	s32 i;

	for (i = 0; i < 3; i++) {
		arg0->unk4[i] = func_8004B888(i + 0x297);
	}
	return func_80065F38(4, 127, 41, 66, 3, 0, &arg0->unk4, 3, 5, 0xC00000, 0, 0, 1);
}
